// import React, { useState } from "react"

// const ParentChild=()=>{

//     const service=[
//         {
//           "ServiceID": 31072503,
//           "ParentServiceID": "",
//           "ServiceTitle": "Class 1",
//           "VagaroServiceID": "",
//           "IsActive": "FALSE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 0,
//           "CategoryID": 72,
//           "ServiceLevel": 0,
//           "ServiceOrder": 1,
//           "BusinessID": 554855,
//           "EventType": 2
//         },
//         {
//           "ServiceID": 31065569,
//           "ParentServiceID": "",
//           "ServiceTitle": "Hair Touch-up and Other",
//           "VagaroServiceID": 4314,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 0,
//           "CategoryID": 72,
//           "ServiceLevel": 0,
//           "ServiceOrder": 2,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065586,
//           "ParentServiceID": 31065569,
//           "ServiceTitle": "Touch-up",
//           "VagaroServiceID": 4002,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 3,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 3,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065588,
//           "ParentServiceID": 31065569,
//           "ServiceTitle": "Touch-up and Blow-Dry",
//           "VagaroServiceID": 4066,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 3,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 4,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065594,
//           "ParentServiceID": 31065569,
//           "ServiceTitle": "qwer",
//           "VagaroServiceID": 31048335,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 0,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 5,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065595,
//           "ParentServiceID": 31065569,
//           "ServiceTitle": "zxcv",
//           "VagaroServiceID": 31048336,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 0,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 6,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065597,
//           "ParentServiceID": 31065569,
//           "ServiceTitle": "qwer",
//           "VagaroServiceID": 31048396,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 0,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 7,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065587,
//           "ParentServiceID": 31065569,
//           "ServiceTitle": "Touch-up and Haircut",
//           "VagaroServiceID": 4058,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 2,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 8,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065589,
//           "ParentServiceID": 31065569,
//           "ServiceTitle": "Touch-up and Flat/Curling Iron",
//           "VagaroServiceID": 4067,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 3,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 9,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065592,
//           "ParentServiceID": 31065569,
//           "ServiceTitle": "Touch-up and Thermal Press",
//           "VagaroServiceID": 27681,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 1,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 10,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065590,
//           "ParentServiceID": 31065569,
//           "ServiceTitle": "Touch-up, Haircut and Blow-Dry",
//           "VagaroServiceID": 4073,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 2,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 11,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065591,
//           "ParentServiceID": 31065569,
//           "ServiceTitle": "Touch-up, Haircut and Flat/Curling Iron",
//           "VagaroServiceID": 4074,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 3,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 12,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065593,
//           "ParentServiceID": 31065569,
//           "ServiceTitle": "Touch-up, Haircut and Thermal Press",
//           "VagaroServiceID": 27682,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 1,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 13,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065596,
//           "ParentServiceID": 31065569,
//           "ServiceTitle": "qwer",
//           "VagaroServiceID": 31048395,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 0,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 14,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065525,
//           "ParentServiceID": "",
//           "ServiceTitle": "Hair Color and Other",
//           "VagaroServiceID": 4311,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 0,
//           "CategoryID": 72,
//           "ServiceLevel": 0,
//           "ServiceOrder": 15,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065527,
//           "ParentServiceID": 31065525,
//           "ServiceTitle": "Color",
//           "VagaroServiceID": 187,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 2,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 16,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065529,
//           "ParentServiceID": 31065525,
//           "ServiceTitle": "Color and Haircut",
//           "VagaroServiceID": 474,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 3,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 17,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065528,
//           "ParentServiceID": 31065525,
//           "ServiceTitle": "Color and Blow-Dry",
//           "VagaroServiceID": 472,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 2,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 18,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065530,
//           "ParentServiceID": 31065525,
//           "ServiceTitle": "Color and Flat/Curling Iron",
//           "VagaroServiceID": 857,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 3,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 19,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065546,
//           "ParentServiceID": 31065525,
//           "ServiceTitle": "Color and Thermal Press",
//           "VagaroServiceID": 27667,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 1,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 20,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065531,
//           "ParentServiceID": 31065525,
//           "ServiceTitle": "Color, Haircut and Blow-Dry",
//           "VagaroServiceID": 868,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 2,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 21,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065532,
//           "ParentServiceID": 31065525,
//           "ServiceTitle": "Color, Haircut and Flat/Curling Iron",
//           "VagaroServiceID": 869,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 3,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 22,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065547,
//           "ParentServiceID": 31065525,
//           "ServiceTitle": "Color, Haircut and Thermal Press",
//           "VagaroServiceID": 27668,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 1,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 23,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065533,
//           "ParentServiceID": 31065525,
//           "ServiceTitle": "Color and Full Highlight",
//           "VagaroServiceID": 4009,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 3,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 24,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065534,
//           "ParentServiceID": 31065525,
//           "ServiceTitle": "Color, Full Highlight and Haircut",
//           "VagaroServiceID": 4016,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 3,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 25,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065535,
//           "ParentServiceID": 31065525,
//           "ServiceTitle": "Color, Full Highlight and Blow-Dry",
//           "VagaroServiceID": 4024,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 2,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 26,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065536,
//           "ParentServiceID": 31065525,
//           "ServiceTitle": "Color, Full Highlight and Flat/Curling Iron",
//           "VagaroServiceID": 4025,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 3,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 27,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065548,
//           "ParentServiceID": 31065525,
//           "ServiceTitle": "Color, Full Highlight and Thermal Press",
//           "VagaroServiceID": 27669,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 1,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 28,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065537,
//           "ParentServiceID": 31065525,
//           "ServiceTitle": "Color, Full Highlight, Haircut and Blow-Dry",
//           "VagaroServiceID": 4031,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 2,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 29,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065538,
//           "ParentServiceID": 31065525,
//           "ServiceTitle": "Color, Full Highlight, Haircut and Flat/Curling Iron",
//           "VagaroServiceID": 4032,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 3,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 30,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065549,
//           "ParentServiceID": 31065525,
//           "ServiceTitle": "Color, Full Highlight, Haircut and Thermal Press",
//           "VagaroServiceID": 27670,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 1,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 31,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065539,
//           "ParentServiceID": 31065525,
//           "ServiceTitle": "Color and Partial Highlight",
//           "VagaroServiceID": 4079,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 3,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 32,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065540,
//           "ParentServiceID": 31065525,
//           "ServiceTitle": "Color, Partial Highlight and Haircut",
//           "VagaroServiceID": 4086,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 3,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 33,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065541,
//           "ParentServiceID": 31065525,
//           "ServiceTitle": "Color, Partial Highlight and Blow-Dry",
//           "VagaroServiceID": 4094,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 2,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 34,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065542,
//           "ParentServiceID": 31065525,
//           "ServiceTitle": "Color, Partial Highlight and Flat/Curling Iron",
//           "VagaroServiceID": 4095,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 3,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 35,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065550,
//           "ParentServiceID": 31065525,
//           "ServiceTitle": "Color, Partial Highlight and Thermal Press",
//           "VagaroServiceID": 27671,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 1,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 36,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065543,
//           "ParentServiceID": 31065525,
//           "ServiceTitle": "Color, Partial Highlight, Haircut and Blow-Dry",
//           "VagaroServiceID": 4101,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 2,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 37,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065544,
//           "ParentServiceID": 31065525,
//           "ServiceTitle": "Color, Partial Highlight, Haircut and Flat/Curling Iron",
//           "VagaroServiceID": 4102,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 3,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 38,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065551,
//           "ParentServiceID": 31065525,
//           "ServiceTitle": "Color, Partial Highlight, Haircut and Thermal Press",
//           "VagaroServiceID": 27672,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 1,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 39,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065545,
//           "ParentServiceID": 31065525,
//           "ServiceTitle": "Color Correction",
//           "VagaroServiceID": 16430,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 1,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 40,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065552,
//           "ParentServiceID": "",
//           "ServiceTitle": "Hair Partial Highlight and Other",
//           "VagaroServiceID": 4313,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 0,
//           "CategoryID": 72,
//           "ServiceLevel": 0,
//           "ServiceOrder": 41,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065570,
//           "ParentServiceID": 31065552,
//           "ServiceTitle": "Partial Highlight",
//           "VagaroServiceID": 3995,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 2,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 42,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065571,
//           "ParentServiceID": 31065552,
//           "ServiceTitle": "Partial Highlight and Haircut",
//           "VagaroServiceID": 4037,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 3,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 43,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065572,
//           "ParentServiceID": 31065552,
//           "ServiceTitle": "Partial Highlight and Blow-Dry",
//           "VagaroServiceID": 4049,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 2,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 44,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065573,
//           "ParentServiceID": 31065552,
//           "ServiceTitle": "Partial Highlight and Flat/Curling Iron",
//           "VagaroServiceID": 4050,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 3,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 45,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065582,
//           "ParentServiceID": 31065552,
//           "ServiceTitle": "Partial Highlight and Thermal Press",
//           "VagaroServiceID": 27677,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 1,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 46,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065574,
//           "ParentServiceID": 31065552,
//           "ServiceTitle": "Partial Highlight, Haircut and Blow-Dry",
//           "VagaroServiceID": 4052,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 2,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 47,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065575,
//           "ParentServiceID": 31065552,
//           "ServiceTitle": "Partial Highlight, Haircut and Flat/Curling Iron",
//           "VagaroServiceID": 4053,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 3,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 48,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065583,
//           "ParentServiceID": 31065552,
//           "ServiceTitle": "Partial Highlight, Haircut and Thermal Press",
//           "VagaroServiceID": 27678,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 1,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 49,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065576,
//           "ParentServiceID": 31065552,
//           "ServiceTitle": "Partial Highlight and Touch-Up",
//           "VagaroServiceID": 4351,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 3,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 50,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065577,
//           "ParentServiceID": 31065552,
//           "ServiceTitle": "Partial Highlight, Touch-Up and Cut",
//           "VagaroServiceID": 4358,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 3,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 51,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065578,
//           "ParentServiceID": 31065552,
//           "ServiceTitle": "Partial Highlight, Touch-Up and Blow-Dry",
//           "VagaroServiceID": 4366,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 2,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 52,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065579,
//           "ParentServiceID": 31065552,
//           "ServiceTitle": "Partial Highlight, Touch-Up and Flat/Curling Iron",
//           "VagaroServiceID": 4367,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 3,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 53,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065584,
//           "ParentServiceID": 31065552,
//           "ServiceTitle": "Partial Highlight, Touch-Up and Thermal Press",
//           "VagaroServiceID": 27679,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 1,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 54,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065580,
//           "ParentServiceID": 31065552,
//           "ServiceTitle": "Partial Highlight, Touch-Up, Haircut and Blow-Dry",
//           "VagaroServiceID": 4373,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 2,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 55,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065581,
//           "ParentServiceID": 31065552,
//           "ServiceTitle": "Partial Highlight, Touch-Up, Haircut and Flat/Curling",
//           "VagaroServiceID": 4374,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 3,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 56,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065585,
//           "ParentServiceID": 31065552,
//           "ServiceTitle": "Partial Highlight, Touch-Up, Haircut and Thermal Press",
//           "VagaroServiceID": 27680,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 1,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 57,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065526,
//           "ParentServiceID": "",
//           "ServiceTitle": "Hair Highlight and Other",
//           "VagaroServiceID": 4312,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 2,
//           "CategoryID": 72,
//           "ServiceLevel": 0,
//           "ServiceOrder": 58,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065553,
//           "ParentServiceID": 31065526,
//           "ServiceTitle": "Highlight",
//           "VagaroServiceID": 478,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 2,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 59,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065554,
//           "ParentServiceID": 31065526,
//           "ServiceTitle": "Highlight and Haircut",
//           "VagaroServiceID": 481,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 3,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 60,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065555,
//           "ParentServiceID": 31065526,
//           "ServiceTitle": "Highlight and Blow-Dry",
//           "VagaroServiceID": 905,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 2,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 61,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065556,
//           "ParentServiceID": 31065526,
//           "ServiceTitle": "Highlight and Flat/Curling Iron",
//           "VagaroServiceID": 906,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 3,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 62,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065565,
//           "ParentServiceID": 31065526,
//           "ServiceTitle": "Highlight and Thermal Press",
//           "VagaroServiceID": 27673,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 1,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 63,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065557,
//           "ParentServiceID": 31065526,
//           "ServiceTitle": "Highlight, Haircut and Blow-Dry",
//           "VagaroServiceID": 912,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 2,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 64,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065558,
//           "ParentServiceID": 31065526,
//           "ServiceTitle": "Highlight, Haircut and Flat/Curling Iron",
//           "VagaroServiceID": 913,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 3,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 65,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065566,
//           "ParentServiceID": 31065526,
//           "ServiceTitle": "Highlight, Haircut and Thermal Press",
//           "VagaroServiceID": 27674,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 1,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 66,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065559,
//           "ParentServiceID": 31065526,
//           "ServiceTitle": "Highlight and Touch-Up",
//           "VagaroServiceID": 4323,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 3,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 67,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065560,
//           "ParentServiceID": 31065526,
//           "ServiceTitle": "Highlight, Touch-Up and Haircut",
//           "VagaroServiceID": 4330,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 3,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 68,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065561,
//           "ParentServiceID": 31065526,
//           "ServiceTitle": "Highlight, Touch-Up and Blow Dry",
//           "VagaroServiceID": 4338,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 2,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 69,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065562,
//           "ParentServiceID": 31065526,
//           "ServiceTitle": "Highlight, Touch-Up and Flat/Curling Iron",
//           "VagaroServiceID": 4339,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 3,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 70,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065567,
//           "ParentServiceID": 31065526,
//           "ServiceTitle": "Highlight, Touch-Up and Thermal Press",
//           "VagaroServiceID": 27675,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 1,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 71,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065563,
//           "ParentServiceID": 31065526,
//           "ServiceTitle": "Highlight, Touch-Up, Haircut and Blow-Dry",
//           "VagaroServiceID": 4345,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 2,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 72,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065564,
//           "ParentServiceID": 31065526,
//           "ServiceTitle": "Highlight, Touch-Up, Haircut and Flat/Curling Iron",
//           "VagaroServiceID": 4346,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 3,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 73,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065568,
//           "ParentServiceID": 31065526,
//           "ServiceTitle": "Highlight, Touch-Up, Haircut and Thermal Press",
//           "VagaroServiceID": 27676,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 1,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 74,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065598,
//           "ParentServiceID": "",
//           "ServiceTitle": "Extensions and Weaving",
//           "VagaroServiceID": 7505686,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 0,
//           "CategoryID": 72,
//           "ServiceLevel": 0,
//           "ServiceOrder": 75,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065599,
//           "ParentServiceID": 31065598,
//           "ServiceTitle": "Extensions / Weaving - Consultation",
//           "VagaroServiceID": 4383,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 3,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 76,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065600,
//           "ParentServiceID": 31065598,
//           "ServiceTitle": "Extensions / Weaving - Implementation",
//           "VagaroServiceID": 4384,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 3,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 77,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065603,
//           "ParentServiceID": 31065598,
//           "ServiceTitle": "Extensions / Weaving - Touch-up",
//           "VagaroServiceID": 7505886,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 0,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 78,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065604,
//           "ParentServiceID": 31065598,
//           "ServiceTitle": "Extensions / Weaving - Removal",
//           "VagaroServiceID": 7505887,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 0,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 79,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065601,
//           "ParentServiceID": 31065598,
//           "ServiceTitle": "Sew-in Weaving",
//           "VagaroServiceID": 7505723,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 0,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 80,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065602,
//           "ParentServiceID": 31065598,
//           "ServiceTitle": "Latch Hook Weaving",
//           "VagaroServiceID": 7505725,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 0,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 81,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31065605,
//           "ParentServiceID": 31065598,
//           "ServiceTitle": "Twists / Braid Crotchet Weaving",
//           "VagaroServiceID": 7505909,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 0,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 82,
//           "BusinessID": 554855,
//           "EventType": 1
//         },
//         {
//           "ServiceID": 31072504,
//           "ParentServiceID": "",
//           "ServiceTitle": "Classes",
//           "VagaroServiceID": 4331964,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 3,
//           "CategoryID": 72,
//           "ServiceLevel": 0,
//           "ServiceOrder": 83,
//           "BusinessID": 554855,
//           "EventType": 2
//         },
//         {
//           "ServiceID": 31072505,
//           "ParentServiceID": 31072504,
//           "ServiceTitle": "Martial Arts",
//           "VagaroServiceID": 4333958,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 0,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 84,
//           "BusinessID": 554855,
//           "EventType": 2
//         },
//         {
//           "ServiceID": 31072506,
//           "ParentServiceID": 31072504,
//           "ServiceTitle": "Kids Martial Arts",
//           "VagaroServiceID": 4333305,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 0,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 85,
//           "BusinessID": 554855,
//           "EventType": 2
//         },
//         {
//           "ServiceID": 31072507,
//           "ParentServiceID": 31072504,
//           "ServiceTitle": "Crossfit",
//           "VagaroServiceID": 4333304,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 0,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 86,
//           "BusinessID": 554855,
//           "EventType": 2
//         },
//         {
//           "ServiceID": 31072508,
//           "ParentServiceID": 31072504,
//           "ServiceTitle": "Barre",
//           "VagaroServiceID": 4333297,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 0,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 87,
//           "BusinessID": 554855,
//           "EventType": 2
//         },
//         {
//           "ServiceID": 31072509,
//           "ParentServiceID": 31072504,
//           "ServiceTitle": "TRX Suspension Training",
//           "VagaroServiceID": 4333296,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 0,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 88,
//           "BusinessID": 554855,
//           "EventType": 2
//         },
//         {
//           "ServiceID": 31072510,
//           "ParentServiceID": 31072504,
//           "ServiceTitle": "Aerobics",
//           "VagaroServiceID": 4331965,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 0,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 89,
//           "BusinessID": 554855,
//           "EventType": 2
//         },
//         {
//           "ServiceID": 31072511,
//           "ParentServiceID": 31072504,
//           "ServiceTitle": "Aqua aerobics",
//           "VagaroServiceID": 4331966,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 0,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 90,
//           "BusinessID": 554855,
//           "EventType": 2
//         },
//         {
//           "ServiceID": 31072512,
//           "ParentServiceID": 31072504,
//           "ServiceTitle": "Belly dancing",
//           "VagaroServiceID": 4331967,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 0,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 91,
//           "BusinessID": 554855,
//           "EventType": 2
//         },
//         {
//           "ServiceID": 31072513,
//           "ParentServiceID": 31072504,
//           "ServiceTitle": "Pole dancing",
//           "VagaroServiceID": 4331968,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 0,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 92,
//           "BusinessID": 554855,
//           "EventType": 2
//         },
//         {
//           "ServiceID": 31072514,
//           "ParentServiceID": 31072504,
//           "ServiceTitle": "Boot camp",
//           "VagaroServiceID": 4331969,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 0,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 93,
//           "BusinessID": 554855,
//           "EventType": 2
//         },
//         {
//           "ServiceID": 31072515,
//           "ParentServiceID": 31072504,
//           "ServiceTitle": "Cycle/spinning",
//           "VagaroServiceID": 4331970,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 0,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 94,
//           "BusinessID": 554855,
//           "EventType": 2
//         },
//         {
//           "ServiceID": 31072516,
//           "ParentServiceID": 31072504,
//           "ServiceTitle": "Pilates",
//           "VagaroServiceID": 4331971,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 0,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 95,
//           "BusinessID": 554855,
//           "EventType": 2
//         },
//         {
//           "ServiceID": 31072517,
//           "ParentServiceID": 31072504,
//           "ServiceTitle": "Yoga",
//           "VagaroServiceID": 4331972,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 0,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 96,
//           "BusinessID": 554855,
//           "EventType": 2
//         },
//         {
//           "ServiceID": 31072518,
//           "ParentServiceID": 31072504,
//           "ServiceTitle": "Kickboxing cardio",
//           "VagaroServiceID": 4331973,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 0,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 97,
//           "BusinessID": 554855,
//           "EventType": 2
//         },
//         {
//           "ServiceID": 31072519,
//           "ParentServiceID": 31072504,
//           "ServiceTitle": "Tai Chi",
//           "VagaroServiceID": 4331974,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 0,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 98,
//           "BusinessID": 554855,
//           "EventType": 2
//         },
//         {
//           "ServiceID": 31072520,
//           "ParentServiceID": 31072504,
//           "ServiceTitle": "Zumba",
//           "VagaroServiceID": 4331975,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 0,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 99,
//           "BusinessID": 554855,
//           "EventType": 2
//         },
//         {
//           "ServiceID": 31072521,
//           "ParentServiceID": 31072504,
//           "ServiceTitle": "Strength training",
//           "VagaroServiceID": 4331976,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 0,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 100,
//           "BusinessID": 554855,
//           "EventType": 2
//         },
//         {
//           "ServiceID": 31072522,
//           "ParentServiceID": 31072504,
//           "ServiceTitle": "Boxing",
//           "VagaroServiceID": 4331977,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 0,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 101,
//           "BusinessID": 554855,
//           "EventType": 2
//         },
//         {
//           "ServiceID": 31072523,
//           "ParentServiceID": 31072504,
//           "ServiceTitle": "Step classes",
//           "VagaroServiceID": 4331978,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 0,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 102,
//           "BusinessID": 554855,
//           "EventType": 2
//         },
//         {
//           "ServiceID": 31072524,
//           "ParentServiceID": 31072504,
//           "ServiceTitle": "U-Jam fitness classes",
//           "VagaroServiceID": 4331979,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 0,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 103,
//           "BusinessID": 554855,
//           "EventType": 2
//         },
//         {
//           "ServiceID": 31072525,
//           "ParentServiceID": 31072504,
//           "ServiceTitle": "Senior group fitness classes",
//           "VagaroServiceID": 4331980,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 0,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 104,
//           "BusinessID": 554855,
//           "EventType": 2
//         },
//         {
//           "ServiceID": 31072526,
//           "ParentServiceID": 31072504,
//           "ServiceTitle": "Resistance band training",
//           "VagaroServiceID": 4331981,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 0,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 105,
//           "BusinessID": 554855,
//           "EventType": 2
//         },
//         {
//           "ServiceID": 31072527,
//           "ParentServiceID": 31072504,
//           "ServiceTitle": "Prenatal classes",
//           "VagaroServiceID": 4331982,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 0,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 106,
//           "BusinessID": 554855,
//           "EventType": 2
//         },
//         {
//           "ServiceID": 31072528,
//           "ParentServiceID": 31072504,
//           "ServiceTitle": "Weight training",
//           "VagaroServiceID": 4331983,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 0,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 107,
//           "BusinessID": 554855,
//           "EventType": 2
//         },
//         {
//           "ServiceID": 31072529,
//           "ParentServiceID": 31072504,
//           "ServiceTitle": "Bollywood dancing",
//           "VagaroServiceID": 4331984,
//           "IsActive": "TRUE",
//           "IsSoftDeleted": "FALSE",
//           "ServiceOrderValues": 0,
//           "CategoryID": 72,
//           "ServiceLevel": 1,
//           "ServiceOrder": 108,
//           "BusinessID": 554855,
//           "EventType": 2
//         }
//       ]
//   const [filteredData, setFilteredData] = useState([]);

//   const ParentService = service.filter((service) => service.ParentServiceID === "");

//   // Handle click on parent to filter and show children
//   const handleClick = (parent) => {
//     const children = service.filter((s) => s.ParentServiceID === parent.ServiceID);
//     setFilteredData(children);  // Set children to state
//   };

//   return (
//     <>
//       <h1>Parent & Childs</h1>
//       <ul>
//         {ParentService.map((parent) => (
//           <li key={parent.ServiceID} onClick={() => handleClick(parent)}>
//             {parent.ServiceTitle}
          
//           {filteredData.length > 0 && (
//         <div>
//            <h3>Child Services:</h3>
//           <ul>
//             {filteredData.map((child) => (
//               <li key={child.ServiceID}>{child.ServiceTitle}</li>
//             ))}
//           </ul>
//         </div>
//       )}
//           </li>
//         ))}
//       </ul>

//       {/* Display child services */}
     
//     </>
//   );
// };

// export default ParentChild